---
builds:
  e13d66ae5ac23c5036a4524149e9e0bce3dc44b1:
    version: e13d66ae5ac23c5036a4524149e9e0bce3dc44b1
    sha1: 6303da8520774a597a0d6cca4f3e5e8c08c64115
    blobstore_id: 83693444-49a8-4077-bc08-56a531fe2648
  810a950d2a996bdaf1573a8e6509fd6f1a924209:
    version: 810a950d2a996bdaf1573a8e6509fd6f1a924209
    sha1: 269bd93783600c4089477b78d429bb27c550e86d
    blobstore_id: 7f93a684-81b0-4617-a8c3-11faeacfe0b9
format-version: '2'
